apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    name: nginx-demo
spec:
  containers:
  - name: nginx-demo
    image: nginx:latest
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
